1lab
Tourie/AndroidLabs pull request #2
Opened 2020-12-08 16:11 UTC by Tourie

2020-12-14 14:26 UTC, gmltA requested changes
Your files contain identical code. Use inheritance to avoid code duplication. Fragments are useless in your project. You should handle view interaction in related fragment. Not in the activity.

2020-12-14 14:26 UTC, gmltA commented on Converter/app/build.gradle
> +        versionName "1.0"
No APK versioning. See requirements.

2020-12-16 17:35 UTC, Tourie commented
I think, now it's loocking better

2020-12-18 13:19 UTC, gmltA approved these changes
A-ha. Now it's better.

2020-12-18 14:00 UTC, merged